export const MARK_ONE = 'MARK_ONE';
export const MARK_ALL = 'MARK_ALL';
export const SHOW_CHILDREN = 'SHOW_CHILDREN';
export const SHOW_MENU = 'SHOW_MENU';
export const CHECK_ONE = 'CHECK_ONE';
export const CHECK_ALL = 'CHECK_ALL';
export const CHECK_ONE_TASK = 'CHECK_ONE_TASK';
export const CHECK_ALL_TASK = 'CHECK_ALL_TASK';

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

export const ENTITY_ASSETS_REQUEST = 'ENTITY_ASSETS_REQUEST';
export const ENTITY_ASSETS_SUCCESS = 'ENTITY_ASSETS_SUCCESS';
export const ENTITY_ASSETS_FAILURE = 'ENTITY_ASSETS_FAILURE';

export const ENTITY_GROUPS_REQUEST = 'ENTITY_GROUPS_REQUEST';
export const ENTITY_GROUPS_SUCCESS = 'ENTITY_GROUPS_SUCCESS';
export const ENTITY_GROUPS_FAILURE = 'ENTITY_GROUPS_FAILURE';

export const ENTITY_SUBTASK_REQUEST = 'ENTITY_SUBTASK_REQUEST';
export const ENTITY_SUBTASK_SUCCESS = 'ENTITY_SUBTASK_SUCCESS';
export const ENTITY_SUBTASK_FAILURE = 'ENTITY_SUBTASK_FAILURE';

export const TASK_ASSETS = 'assets';
export const TASK_GROUPS = 'groups';
export const TASK_PROJECTS = 'projects';